DEFAULT_COINS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "MATICUSDT", "OPUSDT"]
DEFAULT_EXCHANGE = "onus"
SEND_CHANNEL = "Messenger"
USE_VND_DISPLAY = True
BASE_CURRENCY_FOR_SIGNALS = "VND"
AVAILABLE_STRATEGIES = ["Scalping", "Swing"]
MIN_VOLUME = 100000
VOLATILE_THRESHOLD = 5
JUNK_COINS = [
    "PEPEUSDT", "1000BONKUSDT", "DOGE3LUSDT", "SHIB3SUSDT",
    "FLOKIUSDT", "TRUMPUSDT", "WIFUSDT", "SPONGEUSDT", "SATSUSDT"
]
